version: '3.4'

services:
  aery-graphql:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    env_file: ./.env
    volumes:
      - .:/aery-graphql:delegated
      - notused:/aery-graphql/build
    ports:
      - "9090:9090"
    healthcheck:
      disable: true

volumes:
  notused: