version: '3.4'

services:
  go-graphql-mongodb-boilerplate:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    env_file: ./.env
    volumes:
      - .:/go-graphql-mongodb-boilerplate:delegated
      - build:/go-graphql-mongodb-boilerplate/build
    ports:
      - "9090:9090"
    healthcheck:
      disable: true

volumes:
  build:
